export const FETCH_PHOTOS_FAILED = 'FETCH_PHOTOS_FAILED';
export const FETCH_PHOTOS_SUCCEEDED = 'FETCH_PHOTOS_SUCCEEDED';
export const FETCH_AVATAR_FAILED = 'FETCH_AVATAR_FAILED';
export const FETCH_AVATAR_SUCCEEDED = 'FETCH_AVATAR_SUCCEEDED';