version: '3.9'

services:

  postgres:
    volumes:
      - postgres-db-volume:/data
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    container_name: postgres_db
    env_file:
      - env/.env
volumes:
  postgres-db-volume: