export const FETCH_FOLLOWERS_FAILED ='FETCH_FOLLOWERS_FAILED'
export const FETCH_FOLLOWERS_SUCCEEDED = 'FETCH_FOLLOWERS_SUCCEEDED';
export const FETCH_FOLLOWS_FAILED ='FETCH_FOLLOWS_FAILED'
export const FETCH_FOLLOWS_SUCCEEDED = 'FETCH_FOLLOWS_SUCCEEDED';