export const LOAD_USER_DATA_FAILED = 'LOAD_USER_DATA_FAILED';
export const LOAD_USER_DATA_SUCCEEDED = 'LOAD_USER_DATA_SUCCEEDED';
export const LOAD_USER_RELATION_FAILED = 'LOAD_USER_RELATION_FAILED';
export const LOAD_USER_RELATION_SUCCEEDED = 'LOAD_USER_RELATION_SUCCEEDED'
