version: '3.9'

services:

  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
